module_admin = "Admin"

##########
# Config #
##########
mt_admin_conf = "Configure"
md_admin_conf = "Configure and print module variables."
err_module_config_gdt = "There is no config variable matching %s."
err_module_config_gdt_ambiguous = "There are %d matches for %s: %s."
msg_all_modules_conf = "Config: %s."
msg_module_conf = "%s: %s."
msg_module_conf_options = "%s.%s%s is set to %s. Options: %s."
msg_module_conf_changed = "%s.%s has been changed from %s to %s."
msg_module_conf_no_change = "The value for %s in module %s is still %s."

#############
# Dashboard #
#############
mt_admin_dashboard = "Admin Dashboard"
md_admin_dashboard = "Admin Dashboard for your PyGDO installation."


###########
# Modules #
###########
mt_admin_modules = "Modules"
md_admin_modules = "List pygdo modules."

#############
# Configure #
#############
mt_admin_configure = "Configure %s"
md_admin_configure = "Configure a module."
