module_date = "Date"

################
# Date Formats #
################
df_db = "%Y-%m-%d %H:%M:%S.%f"
df_local = "%Y-%m-%d %H:%M"
df_parse = "%m/%d/%Y %H:%M:%S.%f"
df_ms = "%m/%d/%Y %H:%M:%S.%f"
df_long = "%m/%d/%Y %H:%M:%S"
df_short = "%m/%d/%Y %H:%M"
df_day = "%m/%d/%Y"
df_clock = "%H:%M"

##############
# Time Units #
##############
tu_ns = "ns"
tu_us = "Âµs"
tu_ms = "ms"
tu_s = "s"
tu_m = "m"
tu_h = "h"
tu_d = "d"
tu_w = "w"
tu_y = "y"
